j178/prek

.github/workflows/ci.yml, src/cli/run.rs, src/fs.rs, src/languages/python.rs, tests/run.rs
- **Add log file**
- **Merge stderr into stdout**
=> Support `log-file`

src/cli/run.rs, src/languages/python.rs, src/languages/system.rs, src/main.rs, src/run.rs
- **Refactor**
- **flush stdio**
=> Refactor xargs

src/cli/install.rs, src/cli/mod.rs, src/main.rs, tests/install.rs
=> Implement `pre-commit uninstall`

src/cli/mod.rs, src/cli/sample_config.rs, src/main.rs, tests/common/mod.rs, tests/sample_config.rs
=> Implement `pre-commit sample-config`

src/languages/fail.rs, src/languages/mod.rs, tests/language.rs
https://github.com/j178/pre-commit-rs/issues/47
=> feat: add fail language support

Cargo.lock, Cargo.toml, src/languages/fail.rs, src/run.rs, tests/language.rs
=> Use `fancy-regex`

src/cli/hook_impl.rs, src/cli/mod.rs, src/cli/run.rs, src/config.rs, src/main.rs, src/run.rs, tests/common/mod.rs, tests/hook_impl.rs, tests/language.rs, tests/run.rs
=> Implement basic `pre-commit hook-impl`

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/languages/python/impl.rs, src/languages/python/mod.rs, src/languages/python/uv.rs, src/store.rs
- **Auto install uv**
- **Remove setup-uv from ci**
=> Auto install uv

README.md, pyproject.toml
=> Rename pypi package to `pre-commit-rusty`

.github/workflows/ci.yml, .gitignore, Cargo.lock, Cargo.toml, src/languages/python/uv.rs, src/main.rs, src/profiler.rs
=> Add profiler

README.md, src/cli/self_update.rs, src/languages/python/uv.rs
- Pin uv version
- Use unmanaged installation
- Enable installer verbose
=> Improve uv installation

Cargo.lock, Cargo.toml, src/run.rs, tests/hook_impl.rs, tests/language.rs, tests/run.rs
and reduce axoupdater features
=> Improve hook output display

Cargo.lock, Cargo.toml, src/cli/run.rs, src/git.rs, src/languages/docker.rs, src/languages/python/impl.rs, src/languages/system.rs, src/main.rs, src/process.rs, src/run.rs
=> Improve subprocess trace and error output

src/cleanup.rs, src/cli/mod.rs, src/cli/run.rs, src/git.rs, src/main.rs, src/run.rs, tests/common/mod.rs, tests/run.rs
=> Stash working tree before running hooks

Cargo.lock, Cargo.toml, src/languages/python/impl.rs, src/languages/python/uv.rs
=> Support install uv from pypi

Cargo.lock, Cargo.toml, README.md, rust-toolchain.toml, src/builtin/pre_commit_hooks.rs, src/cli/run/filter.rs, src/env_vars.rs, src/fs.rs, src/identify.rs, src/languages/docker.rs, src/languages/mod.rs, src/run.rs, tests/common/mod.rs, tests/run.rs
- **Cargo update**
- **Upgrade rust to 1.84 and upgrade dependencies**
=> Upgrade Rust to 1.84 and upgrade dependencies

.github/workflows/publish.yml, README.md, src/languages/docker.rs, src/languages/docker_image.rs
We have a path dependency now, it can't be published.
=> Do not publish to crates.io

src/config.rs, src/hook.rs, tests/run.rs
=> Support reading `.pre-commit-config.yml` as well

src/builtin/pre_commit_hooks/check_added_large_files.rs, src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs, src/builtin/pre_commit_hooks/mod.rs, src/git.rs
=> feat: 🎸 add check_added_large_files hook

src/languages/mod.rs, src/languages/script.rs
Add script language support for prefligit hooks
Tested with:
- (Precommit) Trailing spaces script
- (Commit-msg) Conventional commit verb script (feat, misc, ...)
(See https://github.com/Assstra/precommit-hooks-test for examples)
Closes #45
=> feat(script): add script hooks support to prefligit

src/cli/run/run.rs, tests/builtin_hooks.rs, tests/clean.rs, tests/common/mod.rs, tests/hook_impl.rs, tests/install.rs, tests/languages/docker_image.rs, tests/languages/fail.rs, tests/run.rs, tests/validate.rs
=> Ignore `config not staged` error for config outside the repo

src/languages/node/installer.rs, src/languages/python/version.rs, src/languages/version.rs, tests/languages/python.rs
=> Support `python311` as a valid language version

src/cli/run/filter.rs, tests/run.rs
Also add a friendly warning for files that aren't exist.
And this PR moves files exist check to only in `--files` case, this should improve performance for `--all-files`.
=> Fix bug that directories are ignored

src/builtin/meta_hooks.rs, src/cli/install.rs, src/cli/reporter.rs, src/cli/run/run.rs, src/hook.rs, src/main.rs, src/workspace.rs
=> Move `Project` into `workspace` module

src/cli/clean.rs
=> Fix cache dir permission before clean

src/languages/python/uv.rs
=> Check minimum supported version for uv found from system

src/identify.rs
=> Fix identify tags for `Pipfile.lock`

.github/workflows/ci.yml, src/languages/python/uv.rs
=> Pin uv version in CI

src/languages/script.rs, tests/languages/main.rs, tests/languages/script.rs
Fixes #397
This doesn't work on Windows yet
=> Fix `script` command path

tests/languages/node.rs, tests/languages/python.rs, tests/run.rs
=> Make error message handling in tests more robust

README.md
=> chore: logo rebranded, Update README.md

src/builtin/pre_commit_hooks/fix_end_of_file.rs
The current implementation in this repository for fixing trailing newlines in files (see PR #392, Related to #294) has achieved its functional goals and has a relatively simple overall structure. However, in practical use, I noticed some room for improvement, mainly including:
- **Multiple file openings**: The current approach opens the file in read-only mode first, then reopens it in write mode, which may cause additional system call overhead and potential race conditions on some platforms.
- **Lack of comprehensive newline statistics**: When the file ends without a newline, the method scans backward from the file's end and adopts the first newline it encounters as the standard, without counting newlines throughout the file. This can lead to inconsistencies, especially if multiple …
=> Avoid reading whole file into memory in `fix_end_of_file` and make it consistent with `pre-commit-hooks`

src/languages/golang/golang.rs, src/languages/golang/installer.rs
To reuse the system go build cahce, to make go build faster.
=> Do not set `GOROOT` and `GOPATH` for system found go

Cargo.lock, Cargo.toml, src/builtin/pre_commit_hooks/check_json.rs, src/builtin/pre_commit_hooks/mod.rs, tests/builtin_hooks.rs
=> Implement `check_json` as built hook

DIFF.md, src/cli/hook_impl.rs, src/cli/mod.rs, src/cli/run/run.rs, src/main.rs, tests/run.rs
=> Support `prek run` multiple hooks

src/run.rs
=> Calculate more accurate max cli length

src/cli/list.rs, src/cli/mod.rs, src/config.rs, src/main.rs, tests/list.rs
=> Support `--output-format=json` in `prek list`

src/cli/run/run.rs, tests/run.rs
=> Add warning for non-existent hook id

src/languages/python/uv.rs
=> Find `uv` alongside the `prek` binary

Cargo.lock, Cargo.toml, src/cli/run/run.rs, src/languages/docker.rs, src/languages/docker_image.rs, src/languages/golang/golang.rs, src/languages/node/node.rs, src/languages/python/python.rs, src/languages/script.rs, src/languages/system.rs, src/main.rs, src/process.rs, src/pty/LICENSE, src/pty/error.rs, src/pty/mod.rs, src/pty/pty.rs, src/pty/sys.rs, src/pty/types.rs, src/run.rs, tests/run.rs
=> Run hooks with pty if color enabled

src/languages/node/installer.rs, src/languages/node/version.rs
=> Support `language_version: lts` for node

src/main.rs, tests/sample_config.rs
=> Adjust `sample-config` file path before writing

src/builtin/pre_commit_hooks/check_added_large_files.rs, src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs, src/hook.rs, src/identify.rs, src/languages/docker.rs, src/languages/docker_image.rs, src/languages/fail.rs, src/languages/golang/golang.rs, src/languages/mod.rs, src/languages/node/node.rs, src/languages/python/python.rs, src/languages/script.rs, src/languages/system.rs, tests/run.rs
=> Resolve script shebang before running

src/cli/mod.rs, src/git.rs, src/main.rs, src/workspace.rs
=> Move GIT_ROOT to a LazyLock

src/config.rs, src/workspace.rs, tests/run.rs
=> Drop support `.yml` config file

README.md
=> fix github release link in README.md

README.md
We use prek at OpenLineage, thanks for @JDarDagran for setting this up. https://github.com/OpenLineage/OpenLineage/pull/3965
=> add OpenLineage to prek users

src/languages/mod.rs, src/languages/script.rs, tests/languages/script.rs
=> Fix `language: script` entry join issue

src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs
=> Fix `trailing-whitespace` cannot handle file contains invalid utf-8 data

src/builtin/pre_commit_hooks/check_toml.rs, src/builtin/pre_commit_hooks/mod.rs
Fixes #556
Signed-off-by: Frost Ming <me@frostming.com>
=> fix: Implement `pre-commit-hooks:check-toml`

src/config.rs, src/identify.rs
Closes https://github.com/j178/prek/issues/432
=> Add validation for file type tags

src/cli/list.rs, src/cli/run/run.rs, tests/list.rs, tests/workspace.rs
=> Support `prek list` in workspace mode

src/cli/hook_impl.rs, src/git.rs, tests/hook_impl.rs
=> Implement `pre-push` hook type

src/cli/auto_update.rs, src/workspace.rs, tests/auto_update.rs
Closes #594 
- **Implement `auto-update` in workspace mode**
- **Deduplicate remote hooks**
=> Implement `auto-update` in workspace mode

src/cli/install.rs, src/cli/run/run.rs, src/languages/pygrep/pygrep.rs, src/store.rs
And fixed an issue that `pygrep` env dependencies are not persisted in `.prek-repo.json`.
=> Improve hook install concurrency

docs/diff.md, lib/constants/src/lib.rs, src/cli/auto_update.rs, src/cli/hook_impl.rs, src/cli/mod.rs, src/config.rs, src/hook.rs, src/languages/node/version.rs, src/languages/python/version.rs, src/workspace.rs, tests/auto_update.rs, tests/common/mod.rs, tests/install.rs, tests/languages/script.rs, tests/run.rs, tests/sample_config.rs, tests/validate.rs
=> Bring back `.pre-commit-config.yml` support

src/builtin/pre_commit_hooks/fix_trailing_whitespace.rs, src/builtin/pre_commit_hooks/mixed_line_ending.rs, src/cli/run/run.rs, src/git.rs, tests/builtin_hooks.rs
=> Fix `trailing-whitespace` & `mixed-line-ending` write file path

Cargo.toml
=> Enable more aggressive optimizations for release

src/languages/docker.rs
=> Run docker container with `--init`

README.md
=> Fix links and warning format in README

lib/constants/src/env_vars.rs, src/cli/run/run.rs, tests/run.rs
From https://github.com/j178/prek/issues/621#issuecomment-3299057336
=> Add a hint when hooks failed in CI

docs/cli.md, src/cli/auto_update.rs, src/cli/mod.rs, src/main.rs, tests/auto_update.rs
=> Add `--dry-run` to `prek auto-update`

src/identify.rs
=> Convert extension to lowercase before checking file tags

src/builtin/pre_commit_hooks/mod.rs
For https://github.com/j178/prek/issues/837#issuecomment-3369223528
=> Add a trace log when running builtin hook
